export const SEARCH_ID = 'SEARCH_ID';
export const SEARCH_ID__SUCCESS = 'SEARCH_ID__SUCCESS';
export const SEARCH_ID__FAIL = 'SEARCH_ID__FAIL';

export const GET_TICKETS = 'GET_TICKETS';
export const GET_TICKETS__SUCCESS = 'GET_TICKETS__SUCCESS';
export const GET_TICKETS__FAIL = 'GET_TICKETS__FAIL';

export const SET_FILTER_CONNECTION = 'SET_FILTER_CONNECTION';
export const SET_FILTER_ASSESSMENT = 'SET_FILTER_ASSESSMENT';
